version: "3.9"



services:
  fismed_be:
    image: fismed-be
    container_name: fismed-be
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - fismed-network
  fismed_db:
    image: postgres:14-alpine
    container_name: fismed-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./demo_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fismed
      - POSTGRES_USER=fismed-user
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_PORT=5432
    networks:
      - fismed-network
networks:
  fismed-network: {}

