services:
  fismed_be_dev:
    image: fismed-be:latest
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      # mode: replicated
      # replicas: 2
      # endpoint_mode: vip
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
