services:
  fismed-be-dev-1:
    container_name: fismed-be-dev-1
    image: fismed-be:latest
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"              # Expose 8081 on the host, 8080 in the container
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - fismed-network
    # healthcheck:  # Health check for service readiness
    #   test: ["CMD", "curl", "-f", "fismed-be-dev-1:8080/api/pemasukan/list", "|", "grep", "status"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

  fismed-be-dev-2:
    container_name: fismed-be-dev-2
    image: fismed-be:latest
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8080"              # Expose 8082 on the host, 8080 in the container
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - fismed-network
    # healthcheck:  # Health check for service readiness
    #   test: ["CMD", "curl", "-f", "fismed-be-dev-2:8080/api/pemasukan/list", "|", "grep", "status"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

networks:
  fismed-network:
    driver: bridge  # Default bridge network

# curl --location --request POST '209.182.237.155:8080/api/pemasukan/list'
# curl --location --request POST 'fismed-be-dev-2:8080/api/proforma-invoice/get-all-list'