services:
  fismed-be-de-1:
    container_name: fismed-be-dev-1
    image: fismed-be:latest
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"
    deploy:
      # mode: replicated
      # replicas: 2
      # endpoint_mode: vip
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - fismed-network
  fismed-be-dev-2:
    container_name: fismed-be-dev-2
    image: fismed-be:latest
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8080"
    deploy:
      # mode: replicated
      # replicas: 2
      # endpoint_mode: vip
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - fismed-network

networks:
  fismed-network:
    driver: bridge
